version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: finanzas_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mi_usuario
      POSTGRES_PASSWORD: mi_password_secreto
      POSTGRES_DB: finanzas_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
